name: 'Rob '
favicon: null
layout_spectrum: 0.06945381686091423
typography_spectrum: 0.02704294165596366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09524288517422974
  lightness: 0.1472158026881516
  saturation: 0.8402672770898789
  rhythmicContrast: 0.034120534313842654
purpose: []
